name: Deploy Frontend to Vercel

on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend-vercel.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        env:
          # Build-time env, must be set as Vercel Project Env variables too for consistency
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (Prebuilt)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

# Required repo secrets:
# - VERCEL_TOKEN: Personal token from Vercel
# - NEXT_PUBLIC_API_BASE_URL: e.g. https://api.your-domain.com
# Optional if you prefer to skip `vercel pull` prompts via env:
# - VERCEL_ORG_ID, VERCEL_PROJECT_ID (set in the environment or use Vercel Git Integration instead)
